name: Publish Docker image

on:
  push:
    branches:
      - lh-test-docker
    tags: '*'
  release:
    types: [published, created]

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Login to Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: cylon-x
          password: ${{ secrets.docker_token }}
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: cylon-x
          password: ${{ secrets.docker_token }}
          registry: ghcr.io
          repository: lcsb-biocore/gigasom.jl/gigasom
          tag_with_ref: true